[package]
name = "rsdd"
version = "0.1.0"
edition = "2018"
authors = ["Steven Holtzen <sholtzen@gmail.com>"]

[lib]
name = "rsdd"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib", "dylib"]

[build]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup,-export-dynamic"]

[dev-dependencies]
criterion = "0.3"
rayon = "1.5.3"
serde_json = "1.0.81"

[[bench]]
name = "rsdd_benchmark"
harness = false


[dependencies]
fnv = "1.0.3"
rand = "0.8.5"
twox-hash = "1.1.0"
dimacs = "0.2.0"
im = "15.1.0"
primal = "0.3.0"
pretty = "0.3.3"
num = "0.1.41"
maplit = "1.0.1"
libc = "0.2"
quickcheck = "1.0.3"
time-test = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "3.2.5", features = ["derive"] }

[profile.release]
debug = true
