[package]
name = "rsdd"
version = "0.1.0"
authors = ["Steven Holtzen <sholtzen@gmail.com>"]

[lib]
name = "rsdd"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib", "dylib"]

[build]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup,-export-dynamic"]

[[bin]]
name = "rsdd-bench"
path = "src/bench/bench.rs"

[dependencies]
fnv = "1.0.3"
rand = "0.3.18"
twox-hash = "1.1.0"
clap = "2.28"
quickersort = "3.0"
dimacs = "0.2.0"
pretty = "0.3.3"
num = "0.1.41"
maplit = "1.0.1"
libc = "0.2"
cudd-sys = {git = "https://github.com/SHoltzen/cudd-sys-1#9f5abbccf69"}


[profile.release]
debug = true
